version: '{build}'
image: Visual Studio 2019
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
dotnet_csproj:
  patch: true
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\**\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/ericbach-ci/api/v2/package
  api_key:
    secure: EIzZ9Il9drXK7E0bOqcMthVTY7v6L3aJsSbR3Jp6MmmGffdGm5WilkrZ4I1Q6RU7
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: sOROaAm8TSr5/SdIy7ZBH34CCZ0m+qRlWUf+FlL1erIgPJ0LQHKJWaEPmYP/nkt+
  on:
    branch: master
    appveyor_repo_tag: true
